services:
  microservicev2.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BuOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant/
      - IdentityOption:Issuer=http://keycloak:8080/realms/MicroServiceTenant
      - ConnectionStrings:Redis=redis.db.basket:6379,password=Password12
    ports:
      - "8080"
    depends_on:
      - redis.db.basket
      - rabbitmq
    restart: always


  microservicev2.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BuOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant/
      - IdentityOption:Issuer=http://keycloak:8080/realms/MicroServiceTenant
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.catalog:27017
    ports:
      - "8080"
    depends_on:
      - mongo.db.catalog
      - rabbitmq
    restart: always


  microservicev2.discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BuOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant/
      - IdentityOption:Issuer=http://keycloak:8080/realms/MicroServiceTenant
      - MongoOption:ConnectionString=mongodb://myuser:Password12@mongo.db.discount:27017
    ports:
      - "8080"
    depends_on:
      - mongo.db.discount
      - rabbitmq
    restart: always


  microservicev2.file.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BuOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant/
      - IdentityOption:Issuer=http://keycloak:8080/realms/MicroServiceTenant
    ports:
      - "8080"
    depends_on:
      - rabbitmq
    restart: always


  microservicev2.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant/
      - IdentityOption:Issuer=http://keycloak:8080/realms/MicroServiceTenant
    ports:
      - "8080"
    restart: always

  microservicev2.order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BuOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant/
      - IdentityOption:Issuer=http://keycloak:8080/realms/MicroServiceTenant
      - AddressUrlOption:PaymentUrl=http://microservicev2.payment.api:8080
      - ConnectionStrings:SqlServer=Server=sqlserver.db.order,1433;Database=OrderDockerDb;User=Sa;Password=Password12*;Trusted_Connection=False;TrustServerCertificate=True;Integrated Security=False
    ports:
      - "8080"
    depends_on:
      - sqlserver.db.order
      - rabbitmq
    restart: always


  microservicev2.payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - BusOption:Address=rabbitmq
      - BuOption:Port=5672
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant/
      - IdentityOption:Issuer=http://keycloak:8080/realms/MicroServiceTenant
    ports:
      - "8080"
    depends_on:
      - rabbitmq
    restart: always


  microservicev2.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Address=http://keycloak:8080/realms/MicroServiceTenant
      - IdentityOption:BaseAddress=http://keycloak:8080
      - MicroServiceOption:Catalog:BaseAddress=http://microservicev2.catalog.api:8080
      - MicroServiceOption:File:BaseAddress=http://microservicev2.file.api:8080
      - MicroServiceOption:Basket:BaseAddress=http://microservicev2.basket.api:8080
      - MicroServiceOption:Discount:BaseAddress=http://microservicev2.discount.api:8080
      - MicroServiceOption:Order:BaseAddress=http://microservicev2.order.api:8080
      - GatewayOption:BaseAddress=http://microservicev2.gateway:8080
    ports:
      - "5050:8080"
    restart: always

